name: Deploy the latest master build to EKS
on:
  workflow_run:
    workflows:
      - Build Docker Image and Push to Docker Hub
    types:
      - completed
  push:
    branches:
      - main
jobs:
  deploy_to_eks_when_pushed_to_master:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.32.1'
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ap-northeast-1
      - name: Connect EKS Cluster to Kubectl
        run:
          aws eks update-kubeconfig --region ap-northeast-1 --name stg-env-cluster
      - name: Apply the Config Files
        run: |
          kubectl apply -f judgement-service-pod.yaml
          kubectl apply -f judgement-service-nodeport.yaml
          
